# Generated by Django 5.1.7 on 2025-03-21 05:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_faq_mindfulnessexercise_moodanalytics_videoresource'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('helpline', 'Helpline'), ('quote', 'Quote')], max_length=20)),
                ('content', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='moodanalytics',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='moodentry',
            name='user_id',
        ),
        migrations.AddField(
            model_name='mindfulnessexercise',
            name='is_challenge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='moodanalytics',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='moodentry',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
